groupId = fr.pinguet62
baseArtifact = wiremock-files-extension
version = 1.0.2
description = Wiremock extension defining helpers for reusing files from the "__files" folder
githubUser = pinguet62
githubRepo = wiremock-files-extension
developer.id = pinguet62
developer.name = PINGUET Julien
developer.email = pinguet62@gmail.com
